#ifndef _MINECRAFT_NETWORK_CLIENTPROTOCOL_H_
#define _MINECRAFT_NETWORK_CLIENTPROTOCOL_H_

enum ClientProtocol
{
    CLIENT_PROTOCOL_CLASSIC = 0,
    CLIENT_PROTOCOL_RAKET_COMPAT,
    CLIENT_PROTOCOL_PROXY_RESERVED
};

#endif /* _MINECRAFT_NETWORK_CLIENTPROTOCOL_H_ */
